import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {FaGithub, FaLinkedin} from 'react-icons/fa';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alexandre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.navContainer}>
          <nav className={styles.nav}>
            <ul>
              <li>
                <a href="https://github.com/AlexandreCamposs"><FaGithub/> GitHub</a>
              </li>
              <li>
                <a href="https://www.linkedin.com/in/alexandre-moura-de-campos-496627114/"><FaLinkedin/> Linkedin</a>
              </li>
            </ul>
          </nav>
        </div>
        <div className="hero">
            <div className="heroText">
              <h1>Hi, my name is Alexandre</h1>
              <p>FrontEnd Developer</p>

              <a href="#">Hire me</a>
              </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
